<?php

/**
* Display help and module information
*/
function pclzip_zip_node_files_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#pclzip_zip_node_files":
      $output = '<p>'.  t("Sends a zip file to the user containing the node files.") .'</p>';
      break;
  }
  return $output;
}

/**
* Valid permissions for this module
*/
function pclzip_zip_node_files_perm() {
  return array('access pclzip_zip_node_files', 'administer pclzip_zip_node_files');
}

/**
* Implementation of hook_menu
*/
function pclzip_zip_node_files_menu() {
  $items = array();

  $items['node/%node/get_zip'] = array(
    'title'                       => 'Get files',
    'page callback'         => 'pclzip_zip_node_files_getzip',
    'page arguments'     => array(1),
    'access arguments'   => array('access pclzip_zip_node_files'),
    'type'                       => MENU_CALLBACK
  );

  $items['admin/settings/pclzip/zip_node_files'] = array(
    'title'                       => t('Zip nodes files'),
    'description'             => t('Settings for the pclzip_zip_node_files module.'),
    'page callback'          => 'drupal_get_form',
    'page arguments'      => array('pclzip_zip_node_files_settings'),
    'access arguments'    => array('administer site configuration'),
    'type'                         => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
* Admin settings
*/
function pclzip_zip_node_files_settings() {

  if (pclzip_library_exists()) {

    // build the admin form
    $form = array();

    $form['pclzip_zip_node_files']['content_type'] = array(
      '#type'           => 'fieldset',
      '#title'            => t('Content Type to show icon'),
      '#collapsible'  => TRUE,
      '#collapsed'    => TRUE,
    );

    // get the content types
    $options = array();
    $query = "SELECT type, name FROM {node_type}";
    $result = db_query($query);
    foreach ($result as $field) {
      $options[$field->type] = $field->name;
    }
    $form['pclzip_zip_node_files']['content_type']['pclzip_zip_node_files_content_type'] = array(
      '#type'                 => 'checkboxes',
      '#title'                  => t('Content Type for nodes'),
      '#options'             => $options,
      '#default_value'  => variable_get('pclzip_zip_node_files_content_type', array('page' =>'page')),
      '#description'       => t('Select the node type where you want the link to appear.'),
    );
    $form['pclzip_zip_node_files']['content_type']['pclzip_zip_node_files_content_type_teaser'] = array(
      '#type'                 => 'checkboxes',
      '#title'                  => t('Content Type for teaser'),
      '#options'             => $options,
      '#default_value'  => variable_get('pclzip_zip_node_files_content_type_teaser', array('page' =>'page')),
      '#description'       => t('Select the node type where you want the link to appear in teaser.'),
    );

    // filename
    $form['pclzip_zip_node_files']['filename'] = array(
      '#type'           => 'fieldset',
      '#title'            => t('Filename for the zip file'),
      '#collapsible'  => TRUE,
      '#collapsed'    => TRUE,
    );
    $form['pclzip_zip_node_files']['filename']['pclzip_zip_node_files_filename'] = array(
      '#type'                 => 'textfield',
      '#title'                  => t('Archive Filename'),
      '#maxlength'       => 255,
      '#default_value'  => variable_get('pclzip_zip_node_files_filename', 'archive'),
      '#description'       => t("Name of the archive file. Don't add the .zip extension."),
    );
    $form['pclzip_zip_node_files']['filename']['help'] = array(
      '#type' => 'item',
      '#description' => t('For the <b>Path to Zip</b> and <b>Archive Filename</b> you can add some vars inside :<br/><ul>'
                                    .'<li>%uid for user id</li>'
                                    .'<li>%name for user name</li>'
                                    .'<li>%nid for node id</li>'
                                    .'<li>%node_title for node title</li>'
                                    .'<li>%year for actual year</li>'
                                    .'<li>%month for actual month</li>'
                                    .'<li>%day for actual day</li></ul>'
                                    .'Spaces will be replaced by undescore "_"'),
    );

    if (module_exists('content')) {
      // manage cck fields
      $form['pclzip_zip_node_files']['pclzip_extra_cck_fields_fieldset'] = array(
        '#type' =>'fieldset',
        '#title' =>t('Extra cck fields'),
        '#collapsible' =>TRUE,
        '#collapsed' =>TRUE,
      );
      $form['pclzip_zip_node_files']['pclzip_extra_cck_fields_fieldset']['pclzip_zip_node_files_extra_cck_fields'] = array(
        '#type'               => 'checkboxes',
        '#title'                => t('CCK Field'),
        '#options'            => pclzip_get_extra_cck_fields(),
        '#default_value'   => variable_get('pclzip_zip_node_files_extra_cck_fields', array()),
        '#description'       => t('Select the CCK field to use.'),
      );
    }
    // manage webfm files
    if (module_exists('webfm')) {
      $form['pclzip_zip_node_files']['pclzip_zip_node_files_use_webfm'] = array(
        '#type'               => 'checkbox',
        '#title'                => t('Use webfm files'),
        '#default_value'   => variable_get('pclzip_zip_node_files_use_webfm', 1),
        '#description'       => t('Select if you want to get webfm files.'),
      );
    }

    return system_settings_form($form);
  }
}

/**
* Implementation of hook_form_alter
*/
function pclzip_zip_node_files_form_alter(&$form, $form_state, $form_id) {
//  if (pclzip_zip_node_files_is_type($form['#type']['#value'], 'node') && (isset($form['attachments']) || pclzip_zip_node_files_has_cck_fields($form) || isset($form['webfm-attach']))) {
  
  if (pclzip_zip_node_files_is_type($form['#type']['#value'], 'node')) {
    if (pclzip_library_exists()) {
      // get download link infos
      $show_link = pclzip_zip_node_files_link_load($form['nid']['#value']);
      $form['pclzip_zip_node_files'] = array(
        '#type'           =>'fieldset',
        '#title'            =>t('Download zip'),
        '#collapsible'  =>TRUE,
        '#collapsed'    =>TRUE,
      );
      $form['pclzip_zip_node_files']['show_download_link'] = array(
        '#type'                   => 'checkbox',
        '#title'                    => t('Show download zip link'),
        '#default_value'    => $form['nid']['#value'] ? $show_link->show_download_link : 1,
        '#description'         => t('Select if you want to show the download zip file link for attachments.'),
      );
      if (pclzip_zip_node_files_is_type($form['type']['#value'], 'teaser')) {
        $form['pclzip_zip_node_files']['show_download_link_teaser'] = array(
          '#type'                  => 'checkbox',
          '#title'                   => t('Show download zip link in teaser'),
          '#default_value'   => $form['nid']['#value'] ? $show_link->show_download_link_teaser : 1,
          '#description'        => t('Select if you want to show the download zip file link for attachments in teaser.'),
        );
      }
    }
  }
}

/**
 * Implementation of hook_node_view.
 */
function pclzip_zip_node_files_node_view($node, $view_mode, $langcode) {
  $show_link = pclzip_zip_node_files_link_load($node->nid);

  // get the files from the node
  $files = pclzip_zip_node_files_get_node_files($node);
  
  // display the link
  if (isset($files) && user_access('access pclzip_zip_node_files') && pclzip_zip_node_files_is_type($node->type, 'node')) {
    if (count($files) && isset($show_link->show_download_link)) {
      if ($view_mode == 'teaser' && (!pclzip_zip_node_files_is_type($node->type, 'teaser') || !$show_link->show_download_link_teaser)) {
        return '';
      }
      if (pclzip_library_exists()) {
        $node->content['pclzip_zip_node_files'] = array(
            '#weight' => 50,
            '#prefix' => '<span class="zip-link">',
            '#markup' =>  l(theme('pclzip_zip_node_files_download_link'), 'node/' . $node->nid . '/get_zip', array('html' => TRUE)),
            '#suffix' => '</span>',
        );
      }
    }
  }
}

/**
 * Implementation of hook_node_update.
 */
function pclzip_zip_node_files_node_update($node){
   pclzip_zip_node_files_link_save($node->nid, $node->show_download_link, $node->show_download_link_teaser);
}

/**
 * Implementation of hook_node_delete.
 */
function pclzip_zip_node_files_node_delete($node){
   pclzip_zip_node_files_link_delete($node->nid);
}


/**
* Get the fields from the node
*/
function pclzip_zip_node_files_get_node_fields($node) {

  $available_fields = array();  
  $fields = field_info_fields();
  $allowed_types = variable_get('pclzip_available_fields', array('image,file'));
  
   foreach ($fields as $field_name => $field) {
    $bundles = array();
    foreach ($field['bundles'] as $available_bundles) {
      $bundles = array_merge($bundles,$available_bundles);
    }
    if (in_array($node->type, $bundles)) {
      if (in_array($field['type'], $allowed_types)) {
        $available_fields[$field['field_name']] = $field['field_name'];
      }
    }
  }
  return $available_fields;
}

/**
* Get the files from the node
*/
function pclzip_zip_node_files_get_node_files($node) {

  $available_fields = pclzip_zip_node_files_get_node_fields($node);
  $nodefiles = array();
  
  foreach ($available_fields as $field){
    $nodefields = field_get_items('node', $node, $field, $node->language);
    
     foreach($nodefields as $file){
       $nodefiles[] = drupal_realpath($file['uri']);
     }
  }
  
  return $nodefiles;
}

/**
* Load the download link value
*/
function pclzip_zip_node_files_link_load($nid) {
  $zipnode = '';
  $result = db_query('SELECT * FROM {pclzip_zip_node_files} WHERE nid=:nid', array(':nid' =>  $nid));
  
  foreach ($result as $row) {
  // Loop through your query results and do some stuff.

    $zipnode = $row;
}
 return $zipnode; 
}

/**
* Save the download link value
*/
function pclzip_zip_node_files_link_save($nid, $show_download_link, $show_download_link_teaser) {
  $values = new stdclass;
  $values->nid = $nid;
  $values->show_download_link = $show_download_link;
  $values->show_download_link_teaser = $show_download_link_teaser;
  $show_link = pclzip_zip_node_files_link_load($nid);
  if ($show_link->nid) {
    // update entry
    drupal_write_record('pclzip_zip_node_files', $values, 'nid');
  }
  else {
    // insert new entry
    drupal_write_record('pclzip_zip_node_files', $values);
  }
}

/**
* Delete the download link value
*/
function pclzip_zip_node_files_link_delete($nid) {
  db_query('DELETE FROM {pclzip_zip_node_files} WHERE nid=%d', $nid);
}

/**
 * Check if node type is selected
 */
function pclzip_zip_node_files_is_type($type, $place) {
  switch ($place) {
    case 'node':
      $types = variable_get('pclzip_zip_node_files_content_type', array('page' =>'page'));
      break;
    case 'teaser':
      $types = variable_get('pclzip_zip_node_files_content_type_teaser', array('page' =>'page'));
      break;
  }
  // rebuild content types
  $allowed_contents = array();
  foreach ($types as $value) {
    array_push($allowed_contents, $value);
  }
  return in_array($type, $allowed_contents, TRUE);
}

/**
 * Implementation of hook_theme().
 */
function pclzip_zip_node_files_theme() {
  return array(
    'pclzip_zip_node_files_download_link'  => array(
      'arguments'     => array(),
      'template'        =>'download_link',
    ),
  );
}

/**
* Helper function to replace the string with defined vars
*/
function pclzip_zip_node_files_str_replacevars($string, $node) {
  global $user;
  $replacers = array(
    // user
    '%uid' =>$user->uid,
    '%name' =>$user->name,
    // node
    '%nid' =>$node->nid,
    '%node_title' =>$node->title,
    // other
    '%year' =>date('Y'),
    '%month' =>date('m'),
    '%day' =>date('d'),
    ' ' =>'_'
  );
  foreach ($replacers as $key=>$value) {
    $string = str_replace($key, $value, $string);
  }
  return $string;
}

/**
* Main function
*/
function pclzip_zip_node_files_getzip($node) {
  // get the files paths from the node
  $files = pclzip_zip_node_files_get_node_files($node);

  // return an error if no files
  if (empty($files)) {
    drupal_set_message(t('No files for this node'), 'error');
    drupal_goto();
    return;
  }

  // get the filename
  $filename = pclzip_zip_node_files_str_replacevars(variable_get('pclzip_zip_node_files_filename', 'archive'), $node).".zip";

  // create the archive
  $archive =& module_invoke("pclzip", 'build_archive', $filename);
  $v_list = $archive->add($files, PCLZIP_OPT_REMOVE_ALL_PATH);

  if ($v_list == 0) {
    drupal_set_message($archive->errorInfo(true), 'error');
    drupal_goto();
    return;
  }

  // send the archive
  module_invoke("pclzip", 'send_file', $filename);
  drupal_goto();
}